spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/realeye?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 8082
  max-http-header-size: 102400
  servlet:
    context-path: /backend
